# Configuração do Sistema TimeRight - TCC
server:
  port: 8080

spring:
  # Configuração H2 (Desenvolvimento)
  datasource:
    url: jdbc:h2:mem:timeright_db
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # Configuração JPA
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        
  # Console H2 (apenas desenvolvimento)
  h2:
    console:
      enabled: true
      path: /h2-console