# Configuração do Sistema Pizzaria F - TCC
server:
  port: 8080

spring:
  # Configuração SQL Server (Produção)
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=pizzariaf_db;encrypt=false
    username: sa
    password: 123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  
  # Configuração H2 (Desenvolvimento - descomente para usar)
  # datasource:
  #   url: jdbc:h2:mem:pizzariaf_db
  #   driver-class-name: org.h2.Driver
  #   username: sa
  #   password: 
  
  # Configuração JPA
  jpa:
    hibernate:
      ddl-auto: update  # Cria/atualiza tabelas automaticamente
    show-sql: true  # Mostra queries SQL no console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        # dialect: org.hibernate.dialect.H2Dialect  # Para H2
        
  # Console H2 (apenas desenvolvimento)
  h2:
    console:
      enabled: true
      path: /h2-console