server:
  port: 8080
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:sqlserver://bancoia.mssql.somee.com;databaseName=bancoia;encrypt=true;trustServerCertificate=true
    username: Isabelly
    password: "12345678"
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true

  web:
    cors:
      allowed-origin-patterns: "*"
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: false

  mail:
    host: smtp.office365.com
    port: 587
    username: rm94720@estudante.fieb.edu.br
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.office365.com

jwt:
  secret: labellevie_super_secret_jwt_key_2024
  expiration: 86400000

admin:
  email: rm94720@estudante.fieb.edu.br

logging:
  level:
    com.labellevie: DEBUG
    org.springframework.security: DEBUG