server:
  port: 8080

spring:
  application:
    name: labellevie-backend
  
  datasource:
    url: jdbc:h2:mem:labellevie
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

jwt:
  secret: labellevie_super_secret_jwt_key_2024
  expiration: 86400000

logging:
  level:
    com.labellevie: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html