# CONFIGURAÇÃO SIMPLES PARA TCC
# Este arquivo configura o banco de dados e o servidor

server:
  port: 8080  # Porta onde o backend vai rodar

spring:
  # BANCO DE DADOS H2 (em memória - simples para demonstração)
  datasource:
    url: jdbc:h2:mem:timeright_simples
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # CONFIGURAÇÃO DO JPA (para trabalhar com banco)
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop  # Recria as tabelas a cada execução
    show-sql: true  # Mostra os comandos SQL no console
  
  # CONSOLE DO H2 (para visualizar o banco)
  h2:
    console:
      enabled: true
      path: /h2-console

# CONFIGURAÇÃO DE CORS (permite acesso do frontend)
cors:
  allowed-origins: http://localhost:5173